# Generated by Django 4.2.16 on 2024-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask1',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
