# Generated by Django 4.2.16 on 2024-10-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask1_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask1',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task1'),
        ),
    ]
