# Generated by Django 4.2.16 on 2024-10-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask1',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task1'),
        ),
    ]
