# Generated by Django 4.2.16 on 2024-10-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='sub_task_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='polls.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
